//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int ID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public string Company_IBAN { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_Number { get; set; }
    }
}
