//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public string ContractName { get; set; }
        public int CompanyID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdateDate { get; set; }
    }
}
