//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public int ID { get; set; }
        public string Detail { get; set; }
        public string Duration { get; set; }
        public string Distance { get; set; }
        public int JobType { get; set; }
    }
}
