//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string Plate { get; set; }
        public int Driver { get; set; }
        public int Company { get; set; }
        public Nullable<decimal> MonthlyCost { get; set; }
        public int SeatCount { get; set; }
    }
}
